# Generated by Django 3.2.20 on 2023-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RI', models.FloatField()),
                ('Na', models.FloatField()),
                ('Mg', models.FloatField()),
                ('AI', models.FloatField()),
                ('Si', models.FloatField()),
                ('K', models.FloatField()),
                ('Ca', models.FloatField()),
                ('Ba', models.FloatField()),
                ('Fe', models.FloatField()),
            ],
        ),
    ]
